# Test code

### Installization

In [1]:
%%bash
cd kmeansmethods
python3 setup.py install

Compiling kmeanscython/kmeansinit_cython.pyx because it changed.
Compiling kmeanscython/kmeansinitpp_cython.pyx because it changed.
Compiling kmeanscython/kmeansinitvv_cython.pyx because it changed.
Compiling kmeanscython/kmeansloop_cython.pyx because it changed.
Compiling kmeanscython/__init__.pyx because it changed.
[1/5] Cythonizing kmeanscython/__init__.pyx
[2/5] Cythonizing kmeanscython/kmeansinit_cython.pyx
[3/5] Cythonizing kmeanscython/kmeansinitpp_cython.pyx
[4/5] Cythonizing kmeanscython/kmeansinitvv_cython.pyx
[5/5] Cythonizing kmeanscython/kmeansloop_cython.pyx
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/kmeanspython
copying kmeanspython/kmeansinit.py -> build/lib.linux-x86_64-3.6/kmeanspython
copying kmeanspython/kmeansinitvv.py -> build/lib.linux-x86_64-3.6/kmeanspython
copying kmeanspython/kmeansinitpp.py -> build/lib.linux-x86_64-3.6/kmeanspython
copying kmeanspython/__init__.py ->

### Load package and prepare data

In [2]:
import pandas as pd
import numpy as np
import random

In [3]:
%%bash
wget https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data

--2018-04-27 20:45:43--  https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.249
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.249|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10782 (11K) [text/plain]
Saving to: ‘wine.data’

     0K ..........                                            100% 57.3M=0s

2018-04-27 20:45:43 (57.3 MB/s) - ‘wine.data’ saved [10782/10782]



In [4]:
testdata = pd.read_csv("wine.data")
testdata = np.array(testdata)

### Test python version

In [5]:
import kmeanspython

In [6]:
init = kmeanspython.kmeansinit(testdata,10);kmeanspython.kmeansloop(testdata, init)

(array([[2.23076923e+00, 1.24676923e+01, 2.13538462e+00, 2.44230769e+00,
         2.17153846e+01, 9.52307692e+01, 2.07692308e+00, 1.89461538e+00,
         4.27692308e-01, 1.39769231e+00, 5.02076915e+00, 9.17692308e-01,
         2.47230769e+00, 4.61384615e+02],
        [2.60000000e+00, 1.26640000e+01, 3.24000000e+00, 2.39533333e+00,
         2.15333333e+01, 9.66000000e+01, 1.85600000e+00, 1.22600000e+00,
         4.24666667e-01, 1.27466667e+00, 4.67533333e+00, 8.64666667e-01,
         2.19533333e+00, 5.73133333e+02],
        [1.04000000e+00, 1.36780000e+01, 1.98920000e+00, 2.37400000e+00,
         1.69680000e+01, 1.03240000e+02, 2.82400000e+00, 2.95920000e+00,
         2.78400000e-01, 1.89200000e+00, 5.18200000e+00, 1.05440000e+00,
         3.15840000e+00, 1.07680000e+03],
        [1.00000000e+00, 1.39205000e+01, 1.76900000e+00, 2.49750000e+00,
         1.72000000e+01, 1.06650000e+02, 2.90800000e+00, 3.08150000e+00,
         2.95500000e-01, 1.90850000e+00, 6.32250000e+00, 1.11700000e+00

In [7]:
init = kmeanspython.kmeansinitpp(testdata,10);kmeanspython.kmeansloop(testdata, init)

(array([[2.21739130e+00, 1.24830435e+01, 2.12086957e+00, 2.34913043e+00,
         2.11000000e+01, 9.26956522e+01, 2.17304348e+00, 1.94956522e+00,
         3.94347826e-01, 1.51913043e+00, 4.40695648e+00, 1.00478261e+00,
         2.44652174e+00, 4.45217391e+02],
        [1.00000000e+00, 1.41366667e+01, 1.83166667e+00, 2.41166667e+00,
         1.62666667e+01, 1.07666667e+02, 3.25500000e+00, 3.49333333e+00,
         2.71666667e-01, 2.21666667e+00, 7.23333333e+00, 1.11333333e+00,
         3.02833333e+00, 1.53033333e+03],
        [2.00000000e+00, 1.29225000e+01, 2.53500000e+00, 2.45500000e+00,
         2.00500000e+01, 1.09000000e+02, 2.16333333e+00, 1.70333333e+00,
         3.62500000e-01, 1.51083333e+00, 5.60916667e+00, 8.48833333e-01,
         2.50416667e+00, 8.56750000e+02],
        [1.00000000e+00, 1.37373684e+01, 2.03526316e+00, 2.34526316e+00,
         1.64368421e+01, 1.01684211e+02, 2.75000000e+00, 2.89947368e+00,
         2.71578947e-01, 1.84736842e+00, 5.19631579e+00, 1.05000000e+00

In [8]:
init = kmeanspython.kmeansinitvv(testdata,10,2);kmeanspython.kmeansloop(testdata, init)

(array([[1.95652174e+00, 1.31652174e+01, 2.64217391e+00, 2.45043478e+00,
         1.93652174e+01, 1.10260870e+02, 2.22521739e+00, 1.77782609e+00,
         3.64347826e-01, 1.57739130e+00, 5.60173913e+00, 8.71565217e-01,
         2.56217391e+00, 8.10478261e+02],
        [1.00000000e+00, 1.40625000e+01, 1.82000000e+00, 2.38000000e+00,
         1.64000000e+01, 1.05250000e+02, 3.10250000e+00, 3.52000000e+00,
         2.62500000e-01, 2.28750000e+00, 7.21250000e+00, 1.19250000e+00,
         2.96750000e+00, 1.56300000e+03],
        [2.00000000e+00, 1.23382353e+01, 2.39117647e+00, 2.22352941e+00,
         2.05294118e+01, 9.01764706e+01, 2.33823529e+00, 2.25823529e+00,
         3.54117647e-01, 1.59470588e+00, 2.79470588e+00, 9.69411765e-01,
         2.95411765e+00, 3.47705882e+02],
        [1.00000000e+00, 1.36554545e+01, 2.00181818e+00, 2.49545455e+00,
         1.67181818e+01, 1.03545455e+02, 2.92363636e+00, 3.11181818e+00,
         2.91818182e-01, 1.99545455e+00, 5.64545455e+00, 1.03727273e+00

### Test cython version

In [9]:
import kmeanscython

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Use importlib.util.find_spec() instead.
  """Entry point for launching an IPython kernel.


In [10]:
init = kmeanscython.kmeansinit_cython(testdata, 10); temp = kmeanscython.kmeansloop_cython(testdata, init);print(temp)
print(np.asarray(temp[0]));print(np.asarray(temp[1]))

(<MemoryView of 'ndarray' at 0x7f60976dfd88>, <MemoryView of 'ndarray' at 0x7f6097713048>, 15, 246821.4541967351)
[[2.50000000e+00 1.28265000e+01 2.29450000e+00 2.32250000e+00
  1.95250000e+01 9.54500000e+01 2.08300000e+00 1.48050000e+00
  4.34500000e-01 1.47050000e+00 6.31050000e+00 8.65000000e-01
  2.18700000e+00 6.75950000e+02]
 [2.00000000e+00 1.29225000e+01 2.53500000e+00 2.45500000e+00
  2.00500000e+01 1.09000000e+02 2.16333333e+00 1.70333333e+00
  3.62500000e-01 1.51083333e+00 5.60916667e+00 8.48833333e-01
  2.50416667e+00 8.56750000e+02]
 [1.28571429e+00 1.35157143e+01 1.73000000e+00 2.39857143e+00
  1.97714286e+01 1.18714286e+02 2.88142857e+00 2.88428571e+00
  2.92857143e-01 2.14285714e+00 4.55285714e+00 1.12000000e+00
  3.21571429e+00 9.57428571e+02]
 [1.00000000e+00 1.37623529e+01 1.78058824e+00 2.54058824e+00
  1.73588235e+01 1.05411765e+02 2.83294118e+00 2.97588235e+00
  3.08235294e-01 1.82352941e+00 5.91647059e+00 1.09529412e+00
  3.03823529e+00 1.27088235e+03]
 [1.000000

In [11]:
init = kmeanscython.kmeansinitpp_cython(testdata, 10); temp = kmeanscython.kmeansloop_cython(testdata, init);print(temp)
print(np.asarray(temp[0]));print(np.asarray(temp[1]))

(<MemoryView of 'ndarray' at 0x7f60976dfbe0>, <MemoryView of 'ndarray' at 0x7f6097713398>, 8, 243580.48582851875)
[[1.86666667e+00 1.29926667e+01 2.37666667e+00 2.45800000e+00
  1.99666667e+01 1.11800000e+02 2.27400000e+00 1.91066667e+00
  3.53333333e-01 1.66866667e+00 5.30066667e+00 9.09066667e-01
  2.63666667e+00 8.70200000e+02]
 [2.07142857e+00 1.32400000e+01 2.96071429e+00 2.39357143e+00
  1.89000000e+01 1.11500000e+02 2.15642857e+00 1.63071429e+00
  3.79285714e-01 1.64285714e+00 5.43785714e+00 8.92142857e-01
  2.47857143e+00 7.51642857e+02]
 [2.00000000e+00 1.23382353e+01 2.39117647e+00 2.22352941e+00
  2.05294118e+01 9.01764706e+01 2.33823529e+00 2.25823529e+00
  3.54117647e-01 1.59470588e+00 2.79470588e+00 9.69411765e-01
  2.95411765e+00 3.47705882e+02]
 [1.00000000e+00 1.37623529e+01 1.78058824e+00 2.54058824e+00
  1.73588235e+01 1.05411765e+02 2.83294118e+00 2.97588235e+00
  3.08235294e-01 1.82352941e+00 5.91647059e+00 1.09529412e+00
  3.03823529e+00 1.27088235e+03]
 [1.000000

In [12]:
init = kmeanscython.kmeansinitvv_cython(testdata, 10, 2); temp = kmeanscython.kmeansloop_cython(testdata, init);print(temp)
print(np.asarray(temp[0]));print(np.asarray(temp[1]))

(<MemoryView of 'ndarray' at 0x7f60976dfd88>, <MemoryView of 'ndarray' at 0x7f60977131f0>, 5, 259706.61466891976)
[[2.32142857e+00 1.29464286e+01 2.70250000e+00 2.36750000e+00
  1.94250000e+01 1.02071429e+02 2.10321429e+00 1.55571429e+00
  4.09642857e-01 1.55107143e+00 5.83892857e+00 8.98928571e-01
  2.29285714e+00 7.05250000e+02]
 [2.32352941e+00 1.25317647e+01 2.28852941e+00 2.31794118e+00
  2.07147059e+01 9.36176471e+01 1.91294118e+00 1.62294118e+00
  4.02647059e-01 1.35088235e+00 4.66970585e+00 9.12941176e-01
  2.33264706e+00 4.83647059e+02]
 [1.00000000e+00 1.39850000e+01 1.83000000e+00 2.56500000e+00
  1.61500000e+01 1.13500000e+02 3.13500000e+00 3.09000000e+00
  3.65000000e-01 1.82500000e+00 6.52500000e+00 1.09000000e+00
  2.89000000e+00 1.41250000e+03]
 [1.12500000e+00 1.36518750e+01 1.93312500e+00 2.27500000e+00
  1.72250000e+01 1.07625000e+02 2.75875000e+00 2.81375000e+00
  2.70625000e-01 1.91625000e+00 4.77687500e+00 1.06562500e+00
  3.23375000e+00 1.02075000e+03]
 [1.000000